//
//  Error.swift
//  SQift
//
//  Created by Christian Noon on 11/8/15.
//  Copyright © 2015 Nike. All rights reserved.
//

import Foundation

/// Used to encapsulate errors generated by SQLite.
public struct SQLiteError: Error {

    // MARK: Properties

    /// The code of the specific error encountered by SQLite: <https://www.sqlite.org/c3ref/c_abort.html>.
    public let code: Int32

    /// The message of the specific error encountered by SQLite: <https://www.sqlite.org/c3ref/errcode.html>.
    public var message: String

    /// A textual description of the error code: <https://www.sqlite.org/c3ref/errcode.html>.
    public var codeDescription: String { return String(cString: sqlite3_errstr(code)) }

    private static let successCodes: Set = [SQLITE_OK, SQLITE_ROW, SQLITE_DONE]

    // MARK: Initialization

    init?(code: Int32, connection: Connection) {
        guard !SQLiteError.successCodes.contains(code) else { return nil }

        self.code = code
        self.message = String(cString: sqlite3_errmsg(connection.handle))
    }
}

// MARK: - CustomStringConvertible

extension SQLiteError: CustomStringConvertible {
    /// A textual representation of the error message, code and code description.
    public var description: String {
        let messageArray = [
            "message=\"\(message)\"",
            "code=\(code)",
            "codeDescription=\"\(codeDescription)\""
        ]

        return "{ " + messageArray.joined(separator: ", ") + " }"
    }
}
